### ISSUE TITLE
I can not figure out how to fetch data from GROQ

### ISSUE THREAD

**Issue by WebRuin** [sanity-io/groq-js#19] opened 2020-06-13 14:55 UTC
I may be wrong, but your API seems to be built only for pushing data to GROQ.  I need is to fetch data from Sanity GROQ and use it in my demo Svelt app.  Maybe I am using the API wrong.

```bash
  onMount(async () => {
    // let dataset = [{_type: "cms", name: "sanity"}]
    let dataset = "*"
    // ^ neither of these are giving me usable data
    let tree = parse(query)
    console.log({tree});
    let value = await evaluate(tree, {dataset})
    console.log({value});
    let data = await value.get()
    console.log(data);
  });
```
yeilds: null

```bash
  onMount(async () => {
    let dataset = [{_type: "cms", name: "sanity"}]
    //let dataset = "*"
    // ^ neither of these are giving me usable data
    let tree = parse(query)
    console.log({tree});
    let value = await evaluate(tree, {dataset})
    console.log({value});
    let data = await value.get()
    console.log(data);
  });
```
yeilds:

```bash
  (1) […]
​    0: Object { name: "sanity" }
​       length: 1
​        <prototype>: [
```
Is your API able to give me an array of objects containing all the data in my Sanity GROQ database?  If so, how. If not, is there another resource that can help me?

**Comment by judofyr** [comment] 2020-06-16 11:50
GROQ-JS is intended to be used for executing GROQ queries in JavaScript when you have all the data locally. If you want to run GROQ against a Sanity data set you should use the HTTP API, either directly (see https://www.sanity.io/docs/http-query) or through the JavaScript client: https://www.npmjs.com/package/@sanity/client

**Comment by judofyr** [comment] 2020-10-12 13:18
Closing this as I believe this not a bug.

**Closed by judofyr** 2020-10-12 13:18 UTC
